name: uptime-kuma 构建并推送镜像

on:
  schedule:
    - cron: '0 0 * * *' # 每天的凌晨 0:00 执行一次，即中国早上8点
  workflow_dispatch: # 手动触发

jobs:
  Uptime-Kuma-Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest

    steps:
      - name: 设置仓库
        uses: actions/checkout@v4
        with:
          repository: louislam/uptime-kuma
          path: uptime-kuma
          fetch-depth: 0

      - name: 检查仓库更新
        id: check_changes
        run: |
          cd uptime-kuma
          git fetch
          LAST_COMMIT=$(git log -1 --format=%ct origin/master)
          CURRENT_TIME=$(date +%s)
          TIME_DIFF=$((CURRENT_TIME - LAST_COMMIT))
          if [ $TIME_DIFF -le 86400 ]; then
            echo "REPO_UPDATED=true" >> $GITHUB_ENV
            echo "仓库在过去24小时内更新过，执行构建"
            LAST_COMMIT_MSG=$(git log -1 --pretty=format:"%s")
            LAST_COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
            LAST_COMMIT_DATE=$(git log -1 --pretty=format:"%ad" --date=format:"%Y-%m-%d %H:%M:%S")
            echo "LAST_COMMIT_MSG=$LAST_COMMIT_MSG" >> $GITHUB_ENV
            echo "LAST_COMMIT_AUTHOR=$LAST_COMMIT_AUTHOR" >> $GITHUB_ENV
            echo "LAST_COMMIT_DATE=$LAST_COMMIT_DATE" >> $GITHUB_ENV
          else
            echo "REPO_UPDATED=false" >> $GITHUB_ENV
            echo "过去24小时内仓库没有更新。跳过构建。"
          fi

      - name: 设置 Docker Buildx
        if: env.REPO_UPDATED == 'true'
        uses: docker/setup-buildx-action@v3

      - name: 登录 Docker Hub
        if: env.REPO_UPDATED == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 创建 Dockerfile
        if: env.REPO_UPDATED == 'true'
        run: |
          cat <<EOF > uptime-kuma/Dockerfile
          # 前端构建阶段
          FROM node:20-alpine as builder

          WORKDIR /app
          COPY package*.json ./
          RUN npm install --legacy-peer-deps && npm cache clean --force
          COPY . .  
          RUN npm run build
          RUN npm prune --production

          # 第二阶段：仅复制构建产物和运行时依赖
          FROM node:20-alpine

          WORKDIR /app
          COPY --from=builder /app/dist ./dist
          COPY --from=builder /app/server ./server
          COPY --from=builder /app/node_modules ./node_modules
          COPY --from=builder /app/package*.json ./
          COPY --from=builder /app/src ./src
          COPY --from=builder /app/db ./db

          EXPOSE 3001
          CMD ["node", "server/server.js"]
          EOF

      - name: 构建并上传镜像
        if: env.REPO_UPDATED == 'true'
        id: build_push
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/uptime-kuma
        run: |
          cd uptime-kuma
          echo 'Building Docker image...'
          docker build -t $IMAGE_NAME:latest .
          echo 'Pushing Docker image to Docker Hub...'
          docker push $IMAGE_NAME:latest

      - name: 获取当前时间
        id: get_time
        run: echo "CURRENT_TIME=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: 发送钉钉通知
        uses: candies404/dingtalk-notify-action@latest
        if: always()
        with:
          dingtalk_token: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
          dingtalk_secret: ${{ secrets.DINGTALK_SECRET }}
          msg_type: markdown
          content: |
              ${{ 
                env.REPO_UPDATED == 'true' && steps.build_push.outcome == 'success' &&
                format('{{"title": "uptime-kuma镜像推送成功", "text": "### uptime-kuma镜像推送成功!\n\n**时间**：{0}\n\n**镜像地址：** https://hub.docker.com/r/{1}/uptime-kuma\n\n**最新更新：**\n- 提交信息：{2}\n- 提交者：{3}\n- 提交时间：{4}"}}', env.CURRENT_TIME, secrets.DOCKERHUB_USERNAME, env.LAST_COMMIT_MSG, env.LAST_COMMIT_AUTHOR, env.LAST_COMMIT_DATE) ||
                env.REPO_UPDATED == 'true' && steps.build_push.outcome != 'success' &&
                format('{{"title": "警告：uptime-kuma镜像推送失败", "text": "### uptime-kuma镜像推送失败!\n\n请尽快检查!!!\n\n**推送时间：** {0}\n\n**最新更新：**\n- 提交信息：{1}\n- 提交者：{2}\n- 提交时间：{3}"}}', env.CURRENT_TIME, env.LAST_COMMIT_MSG, env.LAST_COMMIT_AUTHOR, env.LAST_COMMIT_DATE) ||
                env.REPO_UPDATED != 'true' &&
                format('{{"title": "uptime-kuma仓库无更新", "text": "### uptime-kuma仓库在过去24小时内没有更新\n\n**检查时间：** {0}\n\n**详细信息：** 跳过构建和推送步骤。"}}', env.CURRENT_TIME)
              }}
